[package]
name = "plexmaton-math"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
ratex-parser.workspace = true
ratex-layout.workspace = true
ratex-types.workspace = true
ratex-font.workspace = true
serde.workspace = true
thiserror.workspace = true
unicode-width.workspace = true

[lints]
workspace = true

[dev-dependencies]
serde_json.workspace = true
